### ISSUE TITLE
Solution for handling multiple samples/values in annotation

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseAnnotations#107]
Hi all,

I'd like to discus ways of handling multiple samples in a gene matrix file.  I know we've discussed with @amapeters and @blogsdon  not using the file views for sample tracking, but instead always creating a table that splits sampleIdentifiers by column (this doesn't work when we don't have frozen data releases). But I'd like to float a second idea: adding a 'multiple' or 'none' value to the list of accepted terms.

Should we create a standard way of doing this? Or just address is project-by-project?

**Comment by amapeters** [comment]
Can you give an example

**Comment by sgosline** [comment]
![screen shot 2017-04-04 at 4 33 22 pm](https://cloud.githubusercontent.com/assets/1847866/24683533/803da9f6-1954-11e7-9035-710e0ff10e1a.png)

Here is a subset of a faceted search on a file view - the comma-delimited sampleIdentifier terms are gene matrices, but I also have the original files.  The facets are just too long!!!

**Comment by sgosline** [comment]
Another factor in this discussion is ISA standards for tracking samples: http://isa-specs.readthedocs.io/en/latest/isamodel.html

**Comment by sgosline** [comment]
Goal is to meet as a smaller group (@amapeters @jaeddy #meEEEE @kdaily ) to discuss multiple samples alongside the annotation of clinical terms.

**Comment by sgosline** [comment]
Meeting set for Jan 4!

**Comment by kdaily** [comment]
What a great way to start the New Year's off ~arguing~ discussing! Can't wait!

**Comment by kdaily** [comment]
We converged on the following solution:

1. Annotate the file in question with the following keys as needed: `sampleIdColumn`, `specimenIdColumn`, `sampleMetadataSynId`, `specimenMetadataSynId`.
1. Write a script that can use this data to check, count, etc.

**Comment by sgosline** [comment]
Wait shouldn't we be using `individualIdColumn` and `individualMetadataSynid` instead of `sample` since these match the anotations?

**Comment by teslajoy** [comment]
Also, for our drug target analysis projects, we have data on cell lines with associated metadata. and the annotation key isCellLine.  Can we also include cellLineMetadataSynId. 

Note: for each project, the specimen and individual id of those cell lines may vary.

**Comment by sgosline** [comment]
Let's just stick with the `individualId` and `specimenId` for now.
