### ISSUE TITLE
Should we remove annotations that are always empty?

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseAnnotations#112]
In the update/sync command, can we update the schema to remove all keys for which the value is always blank? Talked to @xindiguo about this, wanting more feedback. I realize this belongs in the synAnnotationsUtils project, but I'm secretly hoping to move those scripts to this repo ;)

**Comment by kdaily** [comment]
:confused:

**Comment by kkdang** [comment]
Sara, can you move this issue to the other repo until (if) they become merged?

**Comment by sgosline** [comment]
Are we going to formally review issues on that repo? It looks like it hasn't been touched in weeks.
