### ISSUE TITLE
How to handle conflicts due to external constraints

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#12]
We should discuss how to handle key conflicts if the key names are being imposed by another entity (consortium or otherwise, for example when data is being deposited first to another source besides Synapse).

**Comment by sgosline** [comment]
Using project-specific annotations you could create an additional annotation dictionary for the other entity, and then append these annotations to the minified. This is already supported in the current implementation.

**Comment by kdaily** [comment]
Provide a mapping dictionary for these projects to do translation.
