### ISSUE TITLE
Add details for NGS library types (re: stranded, paired end)

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/synapseAnnotations#123]
Paired-end and stranded designations are currently boolean flags, but this doesn't capture some of the necessary information for bioinformatics processing tools.

Some useful refs:
https://www.biostars.org/p/64250/ (see top reply)
http://sailfish.readthedocs.io/en/master/library_type.html

See the following suggestions:

```
[
  {
    "name: "readPairOrientation",
    "description": "the relative orientation of the reads in a paired-end protocol", 
    "columnType": "STRING", 
    "maximumSize": 250, 
    "enumValues": [
      {
        "value": "inward",
        "description": "reads face each other",
        "source": ""
      },
      {
        "value": "outward",
        "description": "reads face away from each other",
        "source": ""
      },
      {
        "value": "matching",
        "description": "reads face the same direction",
        "source": ""
      },
    ]
  },
  {
    "name: "readStrandOrigin",
    "description": "the strand from which the read originates in a strand-specific protocol", 
    "columnType": "STRING", 
    "maximumSize": 250, 
    "enumValues": [
      {
        "value": "forward",
        "description": "read 1 (or unpaired read) comes from the forward strand and read 2 (if applicable) comes from the reverse strand; equivalent to Tophat 'fr-secondstrand' type",
        "source": ""
      },
      {
        "value": "reverse",
        "description": "read 1 (or unpaired read) comes from the reverse strand and read 2 (if applicable) comes from the forward strand; equivalent to Tophat 'fr-firststrand' type",
        "source": ""
      },
    ]
  }
]
```

(cc: @ychae, @kdaily, @kkdang, @sgosline)

**Comment by sgosline** [comment]
This term comes from  @amapeters annotation library given her experience.  I think it's important to capture this stuff but I'm not sure we can re-annotate everything we have going forward. Until we have a use case that requires this level of detail I say we stay with what we have.

**Comment by kdaily** [comment]
![shrug](https://media1.giphy.com/media/720g7C1jz13wI/giphy.gif)

**Comment by kdaily** [comment]
They don't conflict (e.g. keys are different) - so not against it! Seems to be complementary: `isStranded=TRUE` then allows additional (not required) info through `readStrandOrigin`.

**Comment by jaeddy** [comment]
@kdaily yes - I view these as complementary annotations. No need to re-annotate anything, just add additional information when available.

The use case I'm dealing with at the moment is running Sailfish on AMP-AD data. `readPairOrientation` is admittedly more esoteric (probably 99% of cases will be "inward"). However, if anyone wants to specify "stranded" for tools such as Tophat, htseq-count, Sailfish, Salmon, and likely others, the second layer of information (orientation) is typically needed.

**Comment by sgosline** [comment]
This is a good use case - I propose we move forward with this!

**Comment by jaeddy** [comment]
👍 I'd like @kkdang to weigh in on the language before merging anything, but I'll open a PR.

**Comment by jaeddy** [comment]
See PR #128
