### ISSUE TITLE
.gtf fileFormat

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/synapseAnnotations#124]
I just came across .gtf (https://en.wikipedia.org/wiki/Gene_transfer_format) in a project that I'm annotating and was wondering if this is used frequently enough to justify addition to standard sage annotations?

**Comment by jaeddy** [comment]
Yup. I don't know how often anyone will be storing GTF/GFF files on Synapse, but it's definitely a relevant format for many bioinformatics pipelines.
http://www.ensembl.org/info/website/upload/gff.html

**Comment by allaway** [comment]
Thanks @jaeddy. Adding it to next pull request.
