### ISSUE TITLE
blood is in 'tissue' and 'organ'

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#129]

**Comment by allaway** [comment]
Blood as a tissue makes the most sense to me.

**Comment by jaeddy** [comment]
I agree with blood as a tissue (connective tissue, if you wanted a broader category). You could also could also include blood as a type of bodily fluid. I don't think it makes sense to call blood an organ.

**Comment by vortexing** [comment]
Data in the NIH Genomic Data Commons actually has "Primary Site" listed and Blood and Bone Marrow are both included in that list.  Acute myeloid leukemia (AML) samples originate from the bone marrow but the specimens you study to study AML may be either the tissue type of bone marrow OR blood (or both!!).  

Another reason to have both in both would be circulating tumor cells would be isolated from Blood as a tissue but are not part of Blood the organ.  

2 cents.

**Comment by kdaily** [comment]
Who is using blood as an organ? I only opened because I saw it in the JSON.

**Comment by kdaily** [comment]
Leave it in both. It's up to you (you being the person who wants to annotate something about blood).
