### ISSUE TITLE
how to link back to source term definition

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#13]
We are using terms from multiple sources (EDAM, MeSH, Experimental Factor). How (in the YAML/JSON) can this be linked to the description of the term?

**Comment by kdaily** [comment]
This might be part of a larger issue of more information about annotations. One thing we use auto-generated lists of annotations is to provide the info about them to the public. See the following table of annotations:

https://www.synapse.org/#!Synapse:syn5662377/tables/

Which is used (among other things) to create user documentation:

https://www.synapse.org/#!Synapse:syn2862345/wiki/231723

**Comment by sgosline** [comment]
We should update the standard yml/json format to move all values to a list within the key and add in source, a link and then a list of values. 

e.g.
term:
   source: EDAM
   link:  http://edamlink
   comments: why i added this
   values:
      -value1
      -value2
      -value3

**Comment by kdaily** [comment]
description and source in JSON schema. these will not be used when using the JSON schema to create a Synapse Table Schema.
