### ISSUE TITLE
Add use case for copying annotations from one project to another

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/synapseAnnotations#140]

**Comment by xindiguo** [comment]
I would like to be able to update schema via a csv file. Please vote for this Jira. https://sagebionetworks.jira.com/browse/SWC-3627

**Comment by teslajoy** [comment]
re-open issue in synAnnotationUtils

**Comment by sgosline** [comment]
Yes, @teslajoy please in the annotator repo.
