### ISSUE TITLE
dependencies of values between keys

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#160]
Had discussion about dependencies between values across keys (e.g., a column that keeps a name and another column that has an alias for that name). Basically, an alias (which we discussed in the past but shelved due to lack of need).

Best solution was to write tests that at a minimum checks that the two keys have the same number of values (and force merge any PRs that don't pass this test on an as-needed basis).

**Comment by sgosline** [comment]
We don't remember what this is about. Closing for now.
