### ISSUE TITLE
move code to synAnnotationUtils

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#182]
I hate to do this but....

It's getting a bit cumbersome to manage versions with two development life cycles going on - one for the annotations themselves, and another for utility code (mostly @teslajoy's). She and I discussed moving everything code related (except for things related to testing the validity of the JSON files) to `synAnnotationUtils`.

**Comment by kdaily** [comment]
The aye's have it! Will coordinate with @teslajoy.

**Comment by kdaily** [comment]
Check if we can move history of the code files from one repo to another.

**Comment by jaeddy** [comment]
@kdaily - this might be helpful: https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/

**Comment by teslajoy** [comment]
see https://github.com/Sage-Bionetworks/synapseAnnotations/pull/141
