### ISSUE TITLE
Tissue homogenate vs nuclei

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/synapseAnnotations#189]
I have samples from nuclei from a mixture of cell types. It doesn't fit under cellType. Do we have an appropriate key?

**Comment by kdaily** [comment]
maybe add 'unknown' or leave as 'not set'

**Comment by amapeters** [comment]
I'm leaving this open for future discussion since it's also relevant to NeuN+ and -. Those are annotated under cellType, but that's not technically correct

**Comment by amapeters** [comment]
Captured in nucleic_acid_source - bulk nuclei for scRNAseq #339
