### ISSUE TITLE
Hi-C resolution 

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/synapseAnnotations#191]
A measure of Hi-C data is its resolution, ie how many kbs can genomic interactions be measured across. Unsure of what annotation to use

**Comment by kdaily** [comment]
Can two datasets with different resolutions be reasonably compared?

**Comment by sgosline** [comment]
Agreed to use ontology lookup service and create new key if no other exists.

**Comment by amapeters** [comment]
Decided not to use this as an annotation
