### ISSUE TITLE
convert all http to https

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/synapseAnnotations#192]

**Comment by teslajoy** [comment]
Our analysis.json terms Cy5 and Cy3 come from a source which seems to be having issues with file pointers via http or https. see https://github.com/OBOFoundry/purl.obolibrary.org/issues/215

Changing sources to resolve issue.

**Comment by teslajoy** [comment]
Also can't do anything about sources such as 
http://www.informatics.jax.org/allele/MGI:3604148
or NTAP which have http web servers on their end.

**Comment by teslajoy** [comment]
Write test that does 

curl -I http://www.ctf.org/
HTTP/1.1 200 OK

or returns 
HTTP/1.1 301 Moved Permanently
...
Location: https://blob

**Comment by kdaily** [comment]
can't fix.
