### ISSUE TITLE
clarify capitalization/style guide for keys and values

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#206]
How should we write things? Don't ask Strunk and White.

We should `camelCase` keys, but keep values as is (defined from their source), minimize acronyms, and document all of this process into the README.md or CONTRIBUTING.md.

**Comment by kdaily** [comment]
#195 should be addressed by this - what to do with things like `individualIdSource` where the currently used value seems very general, but the source is very specific (e.g., `Pitt` and `Penn`)

**Comment by kdaily** [comment]
From #203, we discussed what to add if we make up a term that doesn't map to some internal Synapse page - the resolution was to use `source: 'Sage'`

**Comment by sgosline** [comment]
All based on original source, see contributing document.
