### ISSUE TITLE
key-value terms that are indexed in Synapse sort

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/synapseAnnotations#216]
Via @meredithslota : 
Synapse can index <= 5 key-value annotations and show them in Synapse search results. 
1-What terms do we want to use? 
2-How to determine the list of values to include in indexing:
 2.a. Only those defined in Sage JSON dictionary.
2.b. All values in use for key (risk - vandalism)
2.c Curated list of Sage JSON values and other values currently in use.

**Comment by kkdang** [comment]
Decisions for now:
Go with option 2.c to start.

**Comment by meredithslota** [comment]
Turns out that we currently implement 2b in the platform and changing it is problematic. We will go ahead with 2b and test with the "consortium" term to see how it goes.
