### ISSUE TITLE
Confirm list of "consortium" values in sageCommunity.json

### ISSUE THREAD

**Issue by heymeredith** [Sage-Bionetworks/synapseAnnotations#230]
Values listed in sageCommunity.json for key = consortium are as follows, with partial counts attached: 
- CMC (1980)
- PEC (8981)
- AMP-AD (36842)
- MODEL-AD (86)
- M2OVE-AD (1039)
- BSMN (363)
- CSBC (453)
- PSON (188613)
- GENIE (15434)
- Synodos NF1 (0)
- Synodos NF2 (0)
- Synosos LGG (0)
- DHART SPORE (0)
- Not Applicable (596)

However, the following values have recently been found in a query across this key: 
- AD-CCD (64)
- BeatAML (8)
- beatAML (112 - indicates the above is a typo)
- Cell Culture (10)
- Francis Collins (4)
- Open (12)
- open (1)
- NTAP (2)
- PRO (4)
- PS-ON (17) (should maybe be combined with PSON?)
-Synodos (should be changed to one of the more specific ones?)

If any of the new values are meaningful to Sage, we should add them to the list; otherwise ok to ignore this issue.

**Comment by kdaily** [comment]
@heymeredith can you tell us `projectId`s for `consortium="Not Applicable"`?

**Comment by kdaily** [comment]
@bswhite can you comment on the use of `BeatAML` vs `beatAML` for consortium values?

**Comment by kdaily** [comment]
@amapeters can you confirm `AD-CCD` should or should not be there?

**Comment by kdaily** [comment]
@sgosline can you comment on `Cell Culture`?

**Comment by kdaily** [comment]
@heymeredith these are all ok:

CMC (1980)
PEC (8981)
AMP-AD (36842)
MODEL-AD (86)
M2OVE-AD (1039)
BSMN (363)
CSBC (453)
PSON (188613)
GENIE (15434)
Synodos NF1 (0)
Synodos NF2 (0)
Synodos LGG (0) (**note typo I fixed here)
DHART SPORE (0)

**Comment by kdaily** [comment]
@kdaily will follow up with @heymeredith re: project IDs for other consortium values not commented on here.

**Comment by amapeters** [comment]
AD-CCD - I don't know what that is. I assume an error

**Comment by kdaily** [comment]
@heymeredith don't use `AD-CCD`, please.

**Comment by sgosline** [comment]
I need a bit more context to comment, Cell Culture is an NTAP-funded study spanning multiple projects.

**Comment by kdaily** [comment]
@sgosline the specific question was twofold: 1) is `Cell Culture` an appropriate consortium value (it's not in our annotation dictionary) and 2) should it be promoted to special search status of consortium values in Synapse search?

**Comment by sgosline** [comment]
NTAP funds initiatives that they call 'studies', I have to revisit after my meeting there next week, so can we punt until I'm back in town in November?

**Comment by kdaily** [comment]
Can confirm with @heymeredith but we should move ahead and circle back to this particular one - I imagine it's not too hard to add when we need it, and this only affects 10 files right now?

**Comment by sgosline** [comment]
Yes - I'd prefer not to add `Cell Culture` to the Synapse consortium list at this time.

**Comment by kdaily** [comment]
@bswhite please comment on the use of `BeatAML` vs `beatAML` for consortium values, or risk them being removed from consideration. Thanks!

**Comment by sgosline** [comment]
@meredithslota are these project annotations or file annotations?
