### ISSUE TITLE
SOP for annotating cell lines by individualId and sampleId

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseAnnotations#233]
It will be helpful if we have a standard convention for annotating cell line data. For example - are cell lines individuals? or samples? We have some cell lines that are derived from the same patient but that's not necessarily the status quo. 

I'd like to establish a convention so we can stick to it.

**Comment by kdaily** [comment]
In PCBC and OHSU-LINCS we had standalone annotations for cell line. Important to note OHSU-LINCS annotates down to the aliquot (including growth conditions), but that is not propagated to Synapse.

I feel it's important to put into context of data use - if patient info is important, then cell line may have to go to `sampleId`.

**Comment by sgosline** [comment]
There is also a cellLine annotation for the PSON cell line repository. It's worth discussing adding it to the set, but what do we do for sampleId and patientId for cell line data?

**Comment by sgosline** [comment]
Decision is to create new terms "cellLine" and "cellLineSource" to experimentalData.json.
