### ISSUE TITLE
What are recommended sources for grants

### ISSUE THREAD

**Issue by teslajoy** [Sage-Bionetworks/synapseAnnotations#236]
This issue initiated from #232

**Comment by teslajoy** [comment]
How @ychae has been documenting via reporters' project title & grant numbers as is...
is query-able via python pubmed API's and extremely useful. These grant numbers are umbrella terms, and by some web scraping, you can find the _specific_ project you need. 

Example: https://github.com/teslajoy/synapseRAUtils/blob/master/pubmed-scraper2.py
and https://www.synapse.org/#!Synapse:syn10142562/tables/

I guess I don't recall what explicitly the issue was, but what we have now is ideal and useful.

**Comment by teslajoy** [comment]
^ @sgosline @kdaily can you refresh my memo if I missed something here?

**Comment by kdaily** [comment]
1. What is the lookup mechanism for NSF grants?
1. What other grant sources do we currently have?

**Comment by teslajoy** [comment]
1. NSF:    https://www.nsf.gov/awardsearch/advancedSearch.jsp
2. Department Of Health And Human Services, Grants and Funding (HHS):   https://www.hhs.gov/grants/


Other search mechanisms could be: 
1. grants dot gov   https://www.grants.gov
2. IRIS that is now grant forward     https://www.grantforward.com/search

There are funding sources that are not necessarily searchable. ex. 
https://www.fic.nih.gov/Global/Pages/NGOs.aspx
https://www.insidephilanthropy.com/grants-for-scientific-research/ 
http://www.ascb.org/grants-and-opportunities/where-to-find-research-funding-opportunities/
and some may be state specific: https://research.usc.edu/for-investigators/funding/federal/
http://www.sciencemag.org/news/2015/06/what-do-1-billion-cancer-funding-oregon-university-provide-answer

**Comment by karawoo** [comment]
Closing this as we've stopped enumerating grant values in #523
