### ISSUE TITLE
what dataType to go with assay=CHiP-seq?

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#244]

**Comment by kdaily** [comment]
We looked at ENCODE - they have what we would call `assayTarget = histone` and `assayTarget = transcription factor`. We currently have `assayTarget = H3K9blah`. The question remaining is which is more useful?

**Comment by kdaily** [comment]
Of note in PEC we currently have histone and transcription factor targets (`CTCF`).

**Comment by kdaily** [comment]
@amapeters and @sgosline please weigh in!

**Comment by sgosline** [comment]
Wait is this a question about assayTarget or dataType?

**Comment by sgosline** [comment]
i think the specific histone mark is helpful, I mean k27me3 and k4me3 are diametrically opposed to one another. But I don't have any of this data in my communities so I'm purely arguing from a scientific standpoint.

**Comment by sgosline** [comment]
If we're talking about dataType then i think chromatinActivity is appropriate

**Comment by amapeters** [comment]
We use assayTarget to specify which histone mark, TF, or input

**Comment by amapeters** [comment]
If we use assayTarget - histone, we need an additional level to specify which mark. I prefer it the way it is now

**Comment by sgosline** [comment]
I agree with @amapeters

**Comment by kdaily** [comment]
@sgosline the question @allaway raised is that `chromatinActivity` is not an appropriate value for ChIP-Seq applied to transcription factors, for example.

**Comment by sgosline** [comment]
I disagree - regardless of how you believe TFs to be altering the confirmation of the chromatin alongside histones and molecules like CTCF (which we once called a TF), they are binding to chromatin and altering the activity around them.

**Comment by amapeters** [comment]
Is 'chromatinState' more accurate. Or, we just call it 'epigenomics'?

**Comment by sgosline** [comment]
chromatinState seems so similar it's not worth the change, though I don't mind it if it makes things easier. 

Epigenomics is still a somewhat contested term (I was not allowed to submit it in the title of my 2015 paper for example) last time I checked and can refer to any non-transcriptional regulatory mechanisms such as NMD, miRNA regulation, etc.

**Comment by amapeters** [comment]
chromatinState would also be appropriate for ATACseq (i.e., probing open chromatin)

**Comment by sgosline** [comment]
Sure!

**Comment by kdaily** [comment]
Not all TFs are chromatin associated, as CTCF is though?

**Comment by sgosline** [comment]
I feel like I'm missing the issue here - If you are performing ChIP-Seq you are by definition assaying the chromatin state/activity, regardless of how the TF is directly interacting with it and/or affecting it.

**Comment by kdaily** [comment]
Very true! I thought the `chromatin` in `chromatinActivity` was introduced to described the target - all of our ChIP-Seq data is histone/chromatin modification related. 

If I was coming into a dataset and was looking for TF-binding datasets, knowing that ChIP-Seq is a common technology for that, my first inclination would not be to use `chromatinActivity` as a way to find that.

**Comment by sgosline** [comment]
I'm not entirely sure, if you read through the ENCODE papers it becomes clear that the model of a transcription factor merely activating or repressing transcription is over simplified. So if your intent is to uncover the complete role of TFs in gene regulation you need a lot more than ChIP-Seq data...

**Comment by kdaily** [comment]
ENCODE still thinks it's useful (?) to differentiate in their data between histone and non-histone ChIP-Seq data, per the way they annotate.

**Comment by sgosline** [comment]
If I read correctly, so do we, by specifying the `assayTarget`.

**Comment by amapeters** [comment]
Yes, I thought we decided that already. assay - ChIPseq, assayTarget - specific histone mark or TF

**Comment by amapeters** [comment]
* and input, when no Ab

**Comment by kdaily** [comment]
Their filter is `Assay Category = 'DNA binding'`, then `Target of Assay = ['histone', 'transcription factor', ...]`.

**Comment by kdaily** [comment]
The question is (as @sgosline is getting at) if there is a meaningful distinction between datasets interrogating histone modifications and those that aren't. With the current solution, If I want to find all of either one exclusively, I'm going to have to enumerate histone marks or TF names.

ENCODE seemed to think that it's something users want to be able to do. Not that ENCODE is always right, but we have looked to them as a model in the past.

**Comment by sgosline** [comment]
Not in complete agreement but can re-open when we have more specific use case for transcription factor searches. Decision is to use `chromatinActivity`
