### ISSUE TITLE
Resolve dataType for methylation and ChIPSeq

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseAnnotations#252]
For AMP-AD: currently we're calling the dataType of methylation and ChIPSeq data as "chromatinActivity" but this might not be the best way to go about it. 

Possible alternative: epigenomics for methylation, ChIPSeq, and ATACSeq.

**Comment by sgosline** [comment]
I think we should keep data type as chromatinActivity, both because you are measuring the chromatin directly anyway, and epigenomics is too broad (can apply to post-transcriptional regulation)

**Comment by sgosline** [comment]
Also how is this not a duplicate of #244 ?

**Comment by sgosline** [comment]
Not in complete agreement but can re-open when we have more specific use case for transcription factor searches. Decision is to use `chromatinActivity`
