### ISSUE TITLE
add cellType : iPSC derived neuronal progenitor cells

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseAnnotations#257]

**Comment by sgosline** [comment]
Save for larger discussion about iPSCs to determine if they require an additional annotation key.

**Comment by amapeters** [comment]
Leaving open for cell type discussion

**Comment by kdaily** [comment]
Closing since the PR addresses this issue. @sgosline @amapeters if another issue re: iPSCs is warranted, please open!
