### ISSUE TITLE
need additional fileFormat values for imputed genotypes

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/synapseAnnotations#264]
HBTRC imputed genotypes: syn3981980

The following new fileFormat values were used: dose, erate, info, log, prob, rec

**Comment by sgosline** [comment]
Are these standard file formats?

**Comment by amapeters** [comment]
I don't recognize them, other than dose

**Comment by sgosline** [comment]
Does that mean that they're just csv or tsv or txt files?
