### ISSUE TITLE
analysisType - polygenic score

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/synapseAnnotations#273]
Unsure of what to call this - polygenic score, polygenic risk score? What reference?

**Comment by teslajoy** [comment]
Discovered by https://de.wikipedia.org/wiki/Herman_Nilsson-Ehle (sadly... there are no english language link)

mathematical model: Probability of a phenotype based on genotype + environment (and some covariance).

**polygenic score**  term could be used in laboratory model F1 -> F2 -> F3 design
**polygenic risk score** term is usually used to measure risk of developing a disease

In the context of GWAS these scores are usually generated by PLINK or a wrapper on PLINK (it's ref is gone? http://pngu.mgh.harvard.edu/~purcell/plink/)

given ^ I vote for **polygenic score** and linking to https://en.wikipedia.org/wiki/Polygenic_score

**Comment by kdaily** [comment]
@blogsdon had a good source possibly

**Comment by sgosline** [comment]
Looks like we merged this one with #280 , thanks all!
