### ISSUE TITLE
analysisType - GOenrichment

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/synapseAnnotations#276]

**Comment by kdaily** [comment]
go with gene set enrichment.

**Comment by kdaily** [comment]
actually, use this one http://edamontology.org/operation_3501

**Comment by sgosline** [comment]
@amapeters and @blogsdon can you discuss this to ensure it gets into @blogsdon's updated analysis annotation pull request?

**Comment by blogsdon** [comment]
This is fixed in #321
