### ISSUE TITLE
fileFormat - sdf

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseAnnotations#283]
Illumina has an sdf file format (`Sentrix descriptor file`) that is required to use their BeadScan software. Without it, it displays an error message. 
However, @allaway mentioned that chemical compounds also have an sdf file extension as well (`spatial data file`) that gives locations of structures on the compound. 

The file I'm looking at looks like an xml file and it also seems to give locations:
```
      <RelativeXYZPoint>
        <X>17150</X>
        <Y>9604</Y>
        <Z>0</Z>
      </RelativeXYZPoint>
```

Thoughts on how to proceed? @kdaily @amapeters @sgosline

**Comment by kdaily** [comment]
Add value specific to the format name instead of the extension (use `Sentrix descriptor file`).

**Comment by ychae** [comment]
PR #303
