### ISSUE TITLE
What are global terms for file formats in bioinformatics workflows - revisit fileFormat 

### ISSUE THREAD

**Issue by teslajoy** [Sage-Bionetworks/synapseAnnotations#286]
Given synapse user files: 
What are some of the file formats mime's that synapse excepts in relation to that file format ? 
What to provide to the user if the file format doesn't exist in our dictionary? 

Issue initiated from #239

**Comment by sgosline** [comment]
Then we add them as the annotation need arises, until synapse can detect automatically.
