### ISSUE TITLE
Programmatic access to json

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/synapseAnnotations#288]
I've written some code to make working with the json files here a bit easier, but I'm not sure if this is the best way to go about it. This might be a better fit for annotation utils.

Essentially I've added an `__init__.py` to the `data` folder (and updated `__init__.py` in the parent folder `synapseAnnotations`) so you could do something like this:

```
import synapseAnnotations.data as data
cancer = data.load('cancer')
```

Which gives you a pandas DataFrame with the index containing the annotation keys and columns with all the other info.

|  name | columnType  | description  | enumValues  | 
|---|---|---|---|
| transplantationType  | STRING  | Type of transplantation involved in the experi...  | [{'value': 'allograft', 'description': 'Tissue...  |
| ...  | ...  | ...  | ...  |

Thoughts?

**Comment by teslajoy** [comment]
I wrote a [python script](https://github.com/Sage-Bionetworks/synAnnotationUtils/blob/master/bin/json2synapse.py) that takes in all the json's of a **tag** and normalizes the json data into a [large melted table on synapse](https://www.synapse.org/#!Synapse:syn10242922/tables/). This table is updated after each meeting with all the changes documented in change log with an updated release tag. And we also have a [shiny app](https://github.com/Sage-Bionetworks/annotationUI) that allows the users to subset the data based on "modules" and "keys" or add allows for user defined annotations to be uploaded etc.

We can chat about the flow in process in person too :)

**Comment by teslajoy** [comment]
https://github.com/Sage-Bionetworks/annotator/blob/master/annotator/schema.py#L50

handles this.
