### ISSUE TITLE
Recommended annotations for QC files

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/synapseAnnotations#292]
Is there a recommended annotation for qc files? Maybe ```dataSubtype - qualityControl```?

**Comment by sgosline** [comment]
Xindi can you provide some examples for us to discuss?  I feel like this could fall under metadata...

**Comment by xindiguo** [comment]
For example, files in this folder - https://www.synapse.org/#!Synapse:syn8498844

**Comment by karawoo** [comment]
Was there any resolution to this? Can we close?

**Comment by xindiguo** [comment]
This project had a new schema since I opened this issue. I will close it for now.
