### ISSUE TITLE
should keys have sources?

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#301]
They have descriptions.

**Comment by allaway** [comment]
I vote yes. Most will be "SAGE" but if we are going to use external descriptions (such as Organ, see #302 ) we should attribute that description to the appropriate source.

**Comment by karawoo** [comment]
It seems unlikely anyone is going to have the time to go back through existing keys and add sources. Can we agree that it's ok but not required to add sources to keys?

**Comment by kdaily** [comment]
I can agree!

**Comment by allaway** [comment]
Nearly two year older @allaway also agrees.

**Comment by karawoo** [comment]
Thanks!
