### ISSUE TITLE
compoundDose values

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/synapseAnnotations#305]
```
  {
      "name": "compoundDose",
      "description": "",
      "columnType": "DOUBLE",
      "enumValues": []
  },
```

I have a use case where I am annotating a file with a single compound but a range of log(M) compound doses (-4 to -7.3 log(M)). 

I'd like to annotate the range. Should this be a new key (compoundDoseRange) or should we modify the above key? I'd annotate the compoundDoseUnit as log(M). 

@sgosline

**Comment by sgosline** [comment]
I'm not sure what to do here. I think for dose response curves we need the range, but for images and so forth we only need a single concentration. I like the idea of adding a second key, as much as it pains me.

**Comment by allaway** [comment]
Agreed; will put in PR for new key.
