### ISSUE TITLE
harmonize capitilization of analysis values with source

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/synapseAnnotations#336]
https://github.com/Sage-Bionetworks/synapseAnnotations/pull/321/files

**Comment by philerooski** [comment]
My job's done.

**Comment by sgosline** [comment]
Thanks @philerooski then please flag @blogsdon for review so he can merge. Also we should link this to #321 so it will close when the issue is closed

**Comment by philerooski** [comment]
references #321 

I'm not able to request a reviewer via the side panel. @blogsdon please review.
