### ISSUE TITLE
Create network annotations

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseAnnotations#340]
CSBC will be generating a lot of network data linked through to ndexbio.org. As such I'm wondering what kind of network-specific terms we might need to add. I think 'networkType' might be the only one (genetic, correlative, protein-protein interaction), but there may be more. Any thoughts on this?

**Comment by sgosline** [comment]
Here are some examples of the networks to get the ball rolling:
http://www.ndexbio.org/#/network/199f9bb1-c3eb-11e6-8e29-06603eb7f303
http://www.ndexbio.org/#/network/e50ee3c2-c3d4-11e6-8e29-06603eb7f303 
http://www.ndexbio.org/#/network/13c87f38-c3c1-11e6-8e29-06603eb7f303
http://www.ndexbio.org/#/network/ec8bdae3-c3c9-11e6-8e29-06603eb7f303

**Comment by blogsdon** [comment]
I agree with networkType mapping onto genetic, correlative, ppi, epigenetic, hic, etc.... May also be useful to have a key that describes additional information about the network itself? Like if it's a specific pathway have a key called networkPathwayName ??

**Comment by kdaily** [comment]
Look for existing terms for:

- genetic
- coexpression
- protein-protein interaction
- epigenetic (protein-dna??)
- dna-dna

**Comment by sgosline** [comment]
So 'networkType' wasn't standard, so I opted for 'networkEdgeType', for which I could use more standard terms.

**Comment by sgosline** [comment]
Cloesd by #352
