### ISSUE TITLE
Discussion about mouse behavioral analysis annotations

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseAnnotations#341]
Two of the behavioral rodent assays we have current are novel object recognition and active place avoidance. These values should be added to the `assay` key but further discussion is needed for sources when it comes to behavioral assays.

**Comment by ychae** [comment]
@mjrmason would you be interested in this topic?

**Comment by sgosline** [comment]
I spoked with @mjrmason and it looks like the porcine behavioral studies are rather undefined at this point (because those piggies be CRAZY) so we can move ahead with the mouse suggestions you have.

**Comment by kdaily** [comment]
Use `assay='behavioral'` or something similar.

Then define some new key(s) for what is being measured. @allaway found stuff here: https://www.ebi.ac.uk/ols/ontologies/nbo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000098

**Comment by karawoo** [comment]
This seems resolved in #342, #518: the behavioral tests are listed under `assay` with sources from the Neuro Behavior Ontology or Measurement Method Ontology.
