### ISSUE TITLE
purpose of resourceType, value of some proposed terms?

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/synapseAnnotations#350]
I'd be interested in hearing other peoples thoughts:

I am annotating some data that doesn't really fit the current values for resourceType. Here are some new resourceTypes I'd like to add; do they sound reasonable? The definition of resourceType is a bit vague so I am unsure if these fit in that paradigm.

- chemical names & chemical structures (resourceType value: ID mapping)
- chemical fingerprints ie. hashed representation of chemical structure (resourceType value: hash value)
- manually curated databases of chemical information (resourceType value: curated information)
- programmatically curated large databases (???? still looking for something)

**Comment by allaway** [comment]
copying comments from slack for reference: 

@kdaily  [10:49]
always comes down to the question: how do you (or someone you know) want to be able to use them? e.g., how would having a `resourceType = 'ID mapping'` help solve a search, discovery, or processing problem?

on another note, feel free to make your own `chem.json` and put whatever you want there :wink:

@allaway  [11:04]
hmm

answer - it probably wouldn't - it would just tell you what kind of information is there (edited)
I think chem.json might be a better solution :slightly_smiling_face:
or, cheminformatics.json

@kdaily  [11:49]
@allaway can use as a testing ground - if others start noticing it, or we get redundant, can discuss moving it. although this setup is making me long for more modularity for inclusion/exclusion of specific sets of terms and resources, so it matters less where they 'live'.

@sgosline  [12:01]
This is a good point @allaway, definitely open an issue

**Comment by kdaily** [comment]
what if we moved `experimentalData` to `data`? historically, all the data we were annotating was experimental.

or, we make `curatedData.json` and a `resourceType='curatedData'`?

**Comment by allaway** [comment]
Talked with @kdaily and @sgosline about this more today. The idea to bring to the next meeting is this: 

Break experimentalData up into experimentalData.json and data.json, and create curatedData.json.
data.json would contain keys that apply to both experimentalData and curatedData, such as "dataSubtype" and perhaps "dataType." 

curatedData would then contain keys relevant to files from curated data sources such as: drug databases (eg DrugBank), reference genome files, clinical data, ID maps (e.g. UniProt to HGNC), etc.

**Comment by sgosline** [comment]
Yeah, go ahead and create a PR to discuss!

**Comment by sgosline** [comment]
Let me clarify that last comment - create a PR, make sure it's reviewed/approved, and then we can discuss it!

**Comment by allaway** [comment]
@sgosline @kdaily done in PR #355
