### ISSUE TITLE
modelSystem

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/synapseAnnotations#357]
It is a bit unclear how modelSystem is supposed to be used with the current definition ("Name of model system").

Is this in vivo models only, or do we include this for cell lines, yeast models, etc?
How specific? (mouse, or NOD.Cg-Prkdcscid Il2rgtm1Wjl/SzJ ...)

**Comment by sgosline** [comment]
I believe it's a neuro term, so assigning to @amapeters and @ychae to describe.

**Comment by allaway** [comment]
@sgosline sorry for not being clearer - this is modelSystem in cancer.json (with one value - EVOS_FL_AUTO, which appears to be an imaging system of some type?).

**Comment by sgosline** [comment]
Hmm, I have no idea where this came from....

**Comment by amapeters** [comment]
neuro uses isModelSystem true/false and modelSystemName

**Comment by allaway** [comment]
Offline discussion - we decided to remove this term - we are not sure where it came from.

**Comment by allaway** [comment]
closed by #359
