### ISSUE TITLE
Mouse Strain key

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/synapseAnnotations#362]
We need to clean up our mouse strain annotations. There are 2 keys 'modelSystemName' and 'modelSystemStrainNomenclature'. Neither works. I prefer 'mouseStrain', but wonder if we should use a key that is more inclusive (ie, rat strains, drosophila mutants, etc)

**Comment by ychae** [comment]
Recommended by @blogsdon and @amapeters to use three distinguishing keys: `species`, `strain`, and `background`

**Comment by amapeters** [comment]
Resolved
