### ISSUE TITLE
add unit test to make sure everyone knows the annotation handshake

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#363]
https://twitter.com/sargoshoe/status/975916846674096128

**Comment by kdaily** [comment]
redtri.com/follow-the-parent-traps-guide-to-secret-handshakes/

**Comment by sgosline** [comment]
@kdaily: my sister from another mister...

**Comment by sgosline** [comment]
Also, my real sister and I rocked every handshake around AND knew every line of the parent trap.
