### ISSUE TITLE
Get serious about tool/model annotations

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/synapseAnnotations#364]
Use cases include annotating making systems biology tools/models more "findable" and more systematically connecting data with compatible tools/models. 

What we currently have between the `analysis` and `tool` annotations is a decent start (though the `tool` annotations probably need an overhaul, as they were thrown together more quickly) — however, we probably need some dedicated effort to bring these up to par with data annotations.

Some relevant resources:

+ [**bio.tools**](https://bio.tools/), and in particular, their [**schema**](https://github.com/bio-tools/biotoolsSchema/blob/master/stable/biotools.xsd)
+ [**Systems Biology Ontology (SBO)**](http://www.ebi.ac.uk/sbo/main/)
+ [**SEEK**](https://bmcsystbiol.biomedcentral.com/articles/10.1186/s12918-015-0174-y) — a systems biology data and model management platform
+ [**Mathematical Modeling Ontology (MAMO)**](http://bioportal.bioontology.org/ontologies/MAMO)

**Comment by karawoo** [comment]
Also relevant, though from a different domain: the Ecological Metadata Language's [eml-software](https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/./eml-software.html) module, based on the [open software description format](https://www.w3.org/TR/NOTE-OSD).

**Comment by sgosline** [comment]
Conclusion: modeling annotations are hard to capture without standard use case. Let's have @jaeddy research and report back.

**Comment by karawoo** [comment]
Seems like this isn't a pressing need. If specific tool/model annotation needs arise, we can revisit those. Closing for now.
