### ISSUE TITLE
Need to find solution to cancer subtype

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseAnnotations#366]
Our GBM and BRCA data have subtypes in the annotation, how should we handle this in a generalized fashion.

**Comment by allaway** [comment]
How about annotating oncotree code? http://oncotree.mskcc.org/oncotree/#/home

**Comment by sgosline** [comment]
I think this would be helpful, but this doesn't cover IDH1 subtype in GBM or ER status in breast cancer. Gah.

**Comment by allaway** [comment]
I misunderstood what you meant by subtype. In the case of IDH1 or ER status
that could be captured with a clinicalSubtype key?

**Comment by karawoo** [comment]
@sgosline @allaway do you all still need this?

**Comment by allaway** [comment]
I don't have a need for this in NF.

@milen-sage might see a need for this in HTAN, but cancer subtypes are a little too fluidly defined to be a required annotation IMO.

**Comment by milen-sage** [comment]
Fully agree with Robert - we are not asking for that in HTAN.

**Comment by karawoo** [comment]
Great, I will close this then, thanks!
