### ISSUE TITLE
Broken link for schema definitions

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseAnnotations#397]
[synapseAnnotations](https://github.com/Sage-Bionetworks/synapseAnnotations
)
Under Organization, schema definitions can not be accessed at the link: synapseAnnotations/synapseAnnotations/data/

**Comment by karawoo** [comment]
Thanks for catching that @kelshmo! I opened a PR to fix.

**Comment by karawoo** [comment]
Whoops, actually this should be reopened until the `develop` branch is merged into `master`
