### ISSUE TITLE
review analysis annotations

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/synapseAnnotations#4]
https://github.com/Sage-Bionetworks/synapseAnnotations/blob/analysisAnnotations/minimal_Sage_analysis.yml

**Comment by sgosline** [comment]
Some of these methods are data-type specific (e.g. differential expression).  Should we add a way to distinguish the data type (with some 'integrative' flag)?  Also, how should we add in variant calling, copy number assessment, etc.

**Comment by amapeters** [comment]
does alignment method belong on this list, i.e. should it include data processing? If so, we should think about what other processing annotations should be included. I agree with a data type flag
