### ISSUE TITLE
Should 'breast' be under organ or tissue or both?

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/synapseAnnotations#404]
It looks like under the NCI Thesaurus semantics 'breast' is an organ, but also tissue:
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=18.06d&ns=ncit&code=C12971&key=423781401&b=1&n=null

We currently have 'breast' under organs with the description from EMBL-EBI's ontology:
https://www.ebi.ac.uk/ols/ontologies/bto/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBTO_0000149

in the latter however 'breast' is specified as tissue. Perhaps we can settle on the 'right' ontology for our purposes?

**Comment by karawoo** [comment]
Discussed in 2018-08-28: breast will stay an `organ`

**Comment by allaway** [comment]
Seems like this is resolved.
