### ISSUE TITLE
Add embryo under a new semantic type?

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/synapseAnnotations#405]
Currently we don't have embryonic structure as a semantic type in experimental data annotations, e.g. 
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=18.06d&ns=ncit&code=C28147&key=1009529467&b=1&n=null

A few studies use embryonic stem cells/embryo tissues, and we might need corresponding annotation entries?

**Comment by allaway** [comment]
Is this resolved?

**Comment by milen-sage** [comment]
Yes, that got resolved with the addition of embryonic tissue to 'tissue' and adding various embryonic cell types to 'cellType'.
