### ISSUE TITLE
immunohistochemistry and brightfieldMicroscopy seem to be overlapping assays

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/synapseAnnotations#419]
IHC is generally imaged via brightfield microscopy. We should consider providing guidance on when to use which term.

**Comment by karawoo** [comment]
After discussion on 2018-10-09 we think the best (least-worst?) thing to do for now is guide people to use immunohistochemistry if that is relevant, and brightfield microscopy only for brightfield microscopy that is not immunohistochemistry
