### ISSUE TITLE
platform-related metadata

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#42]
How to capture platform?

Amy P says genomics library kit is uber-important.

Read length?

Relevant to #41.

**Comment by sgosline** [comment]
Can capture platform as well as seq-specific terms including:

- Kit

- Read Length

- Paired-end

**Comment by kdaily** [comment]
https://ndar.nih.gov/experimentView.html?experimentId=511 (can demo this later, it's private)

here's an ENCODE example: https://www.encodeproject.org/platforms/OBI%3A0002021/

**Comment by kdaily** [comment]
@amapeters made a concerted effort to set up array and ngs-specific annotation schemas, moving things out of minified. I think they look fine, but want a second opinion on these (from @sgosline @kkdang @blogsdon):

#63 #65 #66

**Comment by sgosline** [comment]
Is this issue ready to close now?

**Comment by blogsdon** [comment]
looks good to me
