### ISSUE TITLE
annotating isoform data

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/synapseAnnotations#424]
For the RNA-seq Reprocessing we have isoform quantitation data that has been generated with Salmon (alignment free).  There does not exist annotations applied to this data that will allow users to search for it in the AMP-AD file view uniquely.

**Comment by sgosline** [comment]
Is there a PR associated with this?

**Comment by karawoo** [comment]
I asked @blogsdon to make an issue for discussion at the meeting first.

**Comment by blogsdon** [comment]
sounds like the prevailing idea is to have it be a data subtype?

https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=gene_expression

**Comment by karawoo** [comment]
Looking at [this table](https://gdc.cancer.gov/about-data/data-types-and-file-formats/imported-data-types-and-file-formats) I think we could have data type stay the same, data subtype become more specific versions of data type (e.g. `dataType:geneExpression` and `dataSubtype:isoformGeneExpression`). Then per #421 we would add `dataLevel` to capture what's currently in `dataSubtype`.

Can we add additional keys to the definition of terms? If so maybe we can specify the parent of each subtype with something like this:

```
{
        "value": "isoformGeneExpression",
        "description": "blah blah blah",
        "source": "https://foo.org",
        "isSubtypeOf": "geneExpression"
},
```

`isSubtypeOf` would let us keep track of which subtypes go with which types. _Maybe_ there is a way to reflect that in JSON schema as well, I'm not sure.

**Comment by sgosline** [comment]
I like this idea, but this weighs into the larger discussion of whether or not we want to enforce hierarchy in our annotations. To date we've stayed away from this, but I think if we can find maybe a handful of use cases perhaps we can add it. 

@karawoo if we make isSubtypeOf an enum value then maybe that would solve more problems?

**Comment by karawoo** [comment]
Yes the hierarchy thing warrants some careful thinking, because as it stands now we are setting ourselves up for more manual enforcement of our annotations -- `isSubtypeOf` would only tell _us_ that `isoformGeneExpression` is one possible subtype of `geneExpression`. And how many levels of hierarchy are we prepared to support? etc.

**Comment by karawoo** [comment]
Closing this for now. If it comes up again, or we have any new ideas about it, we can reopen.
