### ISSUE TITLE
Moving drug combination data from assay to dataType

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseAnnotations#441]
Currently we (#272) have assigned drug combination screening data the assay of `drugCombinationScreen` instead of `cellViabilityAssay` as it is really measured. Meanwhile the datatype is `drugScreen`. I propose moving the assay back to `cellViability` and moving the dataType to `drugCombinationScreen`. Does anyone have any comments? Uses with similar data (other than @allaway) @milen-sage are there any use cases in CSBC?

**Comment by karawoo** [comment]
I don't think we are using these in neuro, so fine by me

**Comment by sgosline** [comment]
@allaway what do you think about moving dataType and assay?

**Comment by allaway** [comment]
I think this makes sense.
