### ISSUE TITLE
Update Synapse table

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseAnnotations#446]
There are some changes to annotator that need to be made first before the table can be updated to reflect the latest release (10.0.0) -- @milen-sage will make the changes and then run the update.

**Comment by milen-sage** [comment]
Synapse table updated.
annotator updated: 
---- @karawoo; I created a PR in case you'd like to review before merging.

**Comment by karawoo** [comment]
Closing this as the table has been updated (thank you); we can discuss the PR separately over there.
