### ISSUE TITLE
Fix camel case capitalization of annotation terms in new schemas

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseAnnotations#465]
This will be after #464 happens -- the schema.org json that gets generated has an initial capitalization of each term, which doesn't match our existing vocabulary

**Comment by karawoo** [comment]
This is unblocked now that #464 is closed

**Comment by sgosline** [comment]
This is fixed in https://github.com/Sage-Bionetworks/synapseAnnotations/blob/schemaorg-conversion/synapseAnnotations/sage_annotations_2_biothings.py, so once @milen-sage re-runs the script the original keys will be the same.
