### ISSUE TITLE
Add metadataType key

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseAnnotations#470]
In AMP-AD we have multiple types of metadata files containing information on individuals, biospecimens, and the assay that was run. We could use some more granularity to describe the different types of metadata; the current values in `dataType` and `dataSubtype` aren't sufficient.

@amapeters and I are proposing a `metadataType` key that could take values like "clinical" (or "individual"), "biospecimen", "assay". @Sage-Bionetworks/leagueofannotators are there others who would find this useful? Thoughts on the terminology for the key or values? I doubt we will find ontologies that have the right concepts for this, but haven't looked yet.

**Comment by kdaily** [comment]
Would be nice if they map to other 'things' we have: `individualId` and `specimenId` would yield `metadataType = [individual | specimen]` similar to as you are suggesting!

**Comment by kdaily** [comment]
If `metadataType = assay` would the file presumably also have an `assay` key too? That could be useful.

**Comment by karawoo** [comment]
> If metadataType = assay would the file presumably also have an assay key too? That could be useful.

Our templates don't currently have that, but they could

**Comment by amapeters** [comment]
Yes, ir would, for example metadadaType = assay, assay = rnaSeq

**Comment by karawoo** [comment]
Other potential values per hallway conversation with @amapeters and @kdaily: "protocol", "SOP", "data dictionary"

**Comment by sgosline** [comment]
Since we have `analysisType` and `dataType` it makes sense to have `metadataType`

**Comment by karawoo** [comment]
Values we will use for now:
* assay
* biospecimen
* individual
* data dictionary

**Comment by kdaily** [comment]
Can I vote to add in `protocol`?

**Comment by amapeters** [comment]
I second protocol

**Comment by karawoo** [comment]
the feeling in the working group meeting was that protocols and SOPs are more reports/documents than metadata. but I don't object to including protocol if other people are ok with it. we are sharing detailed protocols along with experimental metadata in an upcoming AMP-AD study.

**Comment by amapeters** [comment]
Currently metadata is a value under dataSubtype. Can we add it to dataType?

**Comment by karawoo** [comment]
This is what we talked about in #421, I don't think there was any consensus but "dataLevel" was the closest. But I would be ok with adding dataType: metadata if others support it.
