### ISSUE TITLE
Mouse model annotation

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/synapseAnnotations#497]
@bememea and I would like your feedback on the key for mouse model annotation. We will be annotating all content from each model with the model common name based on Jax or other source's data sheet (ie, we will not try to parse files from the wt littermate control using annotations). People will need to go to the metadata for that.). We use the key isModelSystem = true/false, and thought we would use 'modelSystemName' as the key for the model annotations, but others on the neuro team have suggested modelType. 

Opinions?

**Comment by karawoo** [comment]
I'd prefer modelSystemName, or modelCommonName. modelType seems a bit too broad to me, but I'd be curious to hear why others prefer it.

**Comment by amapeters** [comment]
Anyone else have, or anticipate they will get, mouse model data?

**Comment by amapeters** [comment]
The decision was 'modelSystemName'
