### ISSUE TITLE
what to do with missing data

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#50]
placeholder issue, stand by for details

**Comment by sgosline** [comment]
http://giphy.com/gifs/fallout-4-has-finally-been-announced-gif-zqPm7bAHRu8Xm

**Comment by kdaily** [comment]
Mette and I were discussing strategies for handling missing and/or censored (meaning missing for a known reason) data. I think that it is a per-project issue, too fraught with prior art and programming language specifics to mandate.

Of note, the File View way (and Larsson's TBA sync function) handles truly missing by not setting the annotation at all, as opposed to a sentinel value (which I think is a great way). The View in the web then shows those values as 'Not Set' in facets.
