### ISSUE TITLE
single cell annotations

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseAnnotations#510]
1. single cell 10x data does not follow a standard singleEnd read from 5' method. My understanding (from a user study) is the 10x method uses single end reads from the 3' end, SMARTer v4 produces pairedEnd reads.  @sgosline or @allaway do you have an opinion on whether `3'` could be added as acceptable values to `runType`? Or `runType = singleEnd` in combination with `readStrandOrigin=reverse` is sufficient for this case (though the `singleEnd` definition does not totally conform to this option)?
2. Read 1 and read 2 lengths differ depending on method (e.g. R1 = 28bp for 10x and R1 = 50bp for SMARTer v4, R2 = 91 (or 0) for 10x and R2 = 50bp for SMARTer v4). I am inclined to not track this in the annotations. thoughts?
3. To annotate with QC values or to not annotate with QC values? Our user requested QC metrics live as annotations so that he can appropriately filter samples that do not meet a total read threshold, for example. Again, I am inclined to not track this as an annotation because my understanding of scRNA/ATACseq etc. output is, samples are pooled and would need to be downloaded and parsed anyway. Proposed annotation values are total reads, valid barcodes, number cells, median genes per cell, median UMIs per cell. 

Thanks for your input!

**Comment by allaway** [comment]
@sgosline or @allaway do you have an opinion on whether 3' could be added as acceptable values to runType? Or runType = singleEnd in combination with readStrandOrigin=reverse is sufficient for this case (though the singleEnd definition does not totally conform to this option)?

disclaimer: I don't work with scRNA data. 

I think 10x can use either end, depending on prep method: https://kb.10xgenomics.com/hc/en-us/articles/360000939852-What-is-the-difference-between-Single-Cell-3-and-5-Gene-Expression-libraries-

readStrandOrigin only makes sense for strand specific protocols, which it sounds like this isn't. 

libraryPrepKit might be the best way to encode this information given the above link, but not sure.

**Comment by kelshmo** [comment]
oops sorry @allaway for some reason I have in my head that you work with scRNA.

**Comment by allaway** [comment]
no worries! I probably should know more about it than I do anyway :)

**Comment by sgosline** [comment]
Sorry for the delay on this. I'd recommend looking through the HCA metadata annotations for specific guidance on this, and follow what they do. https://github.com/HumanCellAtlas/metadata-schema/tree/06c1b71988fb38b6ce4ad044c2d5b6641455f6ee/json_schema/type/protocol/sequencing might be close?

**Comment by sgosline** [comment]
Also adding @milen-sage as he might have input.

**Comment by milen-sage** [comment]
Thanks @sgosline, that's useful discussion. For HTAN the current thinking is to not include QC variables in the required scRNASeq metadata and instead provide a link to protocols.io (if people use that to record their protocol). This may change though.

We are recording library layout (single read vs paired end) but not runtype and read strand origin. Again that may change. What are some use cases for recording this detail in terms of analysis?

**Comment by kelshmo** [comment]
@milen-sage I had a working session with a contributor who works with single cell data in both AMPAD and PEC; he advised we surface QC variables in the metadata that lives as annotations to help query useful files. Therefore, we want to validate these values.

**Comment by milen-sage** [comment]
Do they have a specific set of QC variables they'd like to record and what are the values of those that would define useful files for downstream analysis? 

Independent of what we decide to do for HTAN, we can develop schemas for Sage including relevant QC variables (using HCA's variables and/or supplementing with others).

**Comment by kelshmo** [comment]
> 3\. Proposed annotation values are total reads, valid barcodes, number cells, median genes per cell, median UMIs per cell.

The values would be numeric and the accepted QC threshold would be determined by the end-user.

**Comment by milen-sage** [comment]
Thanks! Yes, we can include those in scRNASeq schemas.

**Comment by kelshmo** [comment]
Ok - @cw-dvr8 has those QC variables tracked in our PEC validation schema that [lives here](https://github.com/cw-dvr8/JSON-validation-schemas/blob/master/validation_schemas/psychENCODE/psychENCODE_assay_RNAseq_schema.json).

Regarding my initial proposition:

> 1. single cell 10x data does not follow a standard singleEnd read from 5' method. My understanding (from a user study) is the 10x method uses single end reads from the 3' end, SMARTer v4 produces pairedEnd reads.  @sgosline or @allaway do you have an opinion on whether `3'` could be added as acceptable values to `runType`? Or `runType = singleEnd` in combination with `readStrandOrigin=reverse` is sufficient for this case (though the `singleEnd` definition does not totally conform to this option)?

I decided that `libraryPreparationMethod = 10x` is sufficient to track the 3' end use case. If we get individual cell nucleus data using SMARTer v4 library from the Allen, we will have to add those annotation values. As I understand it, the whole gene body is characterized in this case. Closing issue for now since there is no further action.
