### ISSUE TITLE
values for sex

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseAnnotations#512]
I suggest we update the [accepted values for sex](https://github.com/Sage-Bionetworks/synapseAnnotations/blob/c4c0f4f25c48271877cd596b6356891edbacf1b8/synapseAnnotations/data/experimentalData.json#L1572) to XX, XY and XXY and enforce these values as "values validated quantitatively with SNP genotype" or another platform to validate sex.

If we want to annotate with male and female, the key `gender` is technically correct.

**Comment by amapeters** [comment]
@bememea is using sex = male and female as annotations on AMP portal data. That needs to stay as is. Also, sex specified by chromosome can't be made public in the case of XXY and similar disorders

**Comment by amapeters** [comment]
Although, we could change the key to gender. @kelshmo - please find out if others have used 'sex' as an annotation

**Comment by cw-dvr8** [comment]
"gender" is not currently an annotation, but you do already have a "reportedGender" key in the PsychENCODE schema that is defined as the gender reported by the brain bank, with allowable values of "male"/"female".  Having another key with the term "gender" in it with different allowable values may lead to confusion.

**Comment by amapeters** [comment]
I agree, @bememea can you change the key to 'reportedGender'. We do need to verify if others have used sex = male/female as file annotations

**Comment by karawoo** [comment]
It would not be correct to change our existing sex key to gender. We use it for mice and other non-human organisms, which do not have a gender.

**Comment by sgosline** [comment]
But how would gender apply to cell lines? To animal models that aren't able to define their own gender?

**Comment by karawoo** [comment]
jinx, @sgosline

**Comment by amapeters** [comment]
It would in hindsight have been more correct to have used XX and XY for the animal models, but yes, that is another place it has been used as male/female. Do we have rules against using equal values for different keys? Can we add XX, XY to sex and male/female to reportedGender

**Comment by allaway** [comment]
agree with @karawoo and @sgosline .

**Comment by karawoo** [comment]
Determining sex based on chromosomes alone is also pretty outdated and incomplete. I don't think using these as the values for a "sex" key is a good choice.

**Comment by amapeters** [comment]
What is an alternate key for XX and XY

**Comment by karawoo** [comment]
`sexChromosomes`?

**Comment by amapeters** [comment]
@kelshmo @cw-dvr8 - can we use sexChromosome = XX/XY and a PEC specific key where reportedGender = male/female. We will leave it as is for AMP

**Comment by cw-dvr8** [comment]
I'll change "sex" to "sexChromosome" in the PEC metadata spreadsheet.  reportedGender is currently not a key anywhere except for PEC so we can make the values be whatever we need.
