### ISSUE TITLE
assay = mRNA counts

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/synapseAnnotations#516]
We have mRNA expression data from the NanoString platform and want to use the standard ENCODE uses for NanoString miRNA data 'miRNA counts': https://www.encodeproject.org/experiments/ENCSR822RRV/

miRNA counts is defined in OntoBee as "A microRNA profiling assay using digital molecular barcoding technology to quantify target microRNA molecules without the need for amplification."

There is no definition for mRNA counts. Suggest the following Sage definition "A mRNA profiling assay using digital molecular barcoding technology to quantify target mRNA molecules without the need for amplification." @karawoo - please review

**Comment by karawoo** [comment]
Seems fine to me!
