### ISSUE TITLE
Do we really need to control values for grant?

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseAnnotations#519]
The grant key currently has a controlled list of values. This becomes hard to keep up to date, particularly if we get data contributions from outside the consortium in the future. Do we really need to control the values for this key, or could we change it to allow any string?

https://github.com/Sage-Bionetworks/synapseAnnotations/blob/c4c0f4f25c48271877cd596b6356891edbacf1b8/synapseAnnotations/data/neuro.json#L14-L181

**Comment by cw-dvr8** [comment]
Could you put some pattern matches on it, like it has to start with "U01" or "R01" or "R21" or... ?  That could potentially keep people from putting something totally nonsensical in.

**Comment by karawoo** [comment]
That's something we could definitely do with JSON Schema. Until that transition is complete I don't know that there's a way to represent it or enforce it in our current JSON annotation structure.

**Comment by amapeters** [comment]
I suggest allowing any string, but make sure that we specify the following in the description
"use Activity Code+Institute Code+Serial Number (eg, U01MH103392)"
