### ISSUE TITLE
Allow alternate capitalizations of boolean values

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseAnnotations#535]
TRUE, true, True, etc.

We are constantly having issues with people providing different capitalizations. TRUE/FALSE are the default in R and Excel. And Synapse will treat them all the same regardless of capitalization:
<img width="864" alt="Screen Shot 2019-11-12 at 4 32 23 PM" src="https://user-images.githubusercontent.com/4452678/68722385-22fe8800-056a-11ea-8552-6c83be7d875f.png">

So I propose all boolean annotations be updated to allow any capitalization, either explicitly as enumerated values, or implicitly by removing all the enumerated values and relying solely on the columnType. Thoughts?

**Comment by kdaily** [comment]
I like relying on the column type and removing enumerated values. This translates naturally to JSON schemas that also have a boolean type.

**Comment by cw-dvr8** [comment]
I agree with Kenny.  I think it would introduce a lot of noise to our documentation if we have to list out "True", "TRUE", "true", "tRue", etc. as possible values.
