### ISSUE TITLE
Come up with unified scheme for individual and sample identifiers

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseAnnotations#56]
We have individual/patient identifiers and sample/specimen identifiers in NF and neuro - I think it makes sense to move to minified.

**Comment by kdaily** [comment]
Good point - this was something that was named as specific to some brain bank samples, but is a commonly used field name. We also have `individualId` and `individualIdSource` in neuro.

**Comment by jaeddy** [comment]
If we want to get really intense about labeling samples:
https://wiki.nci.nih.gov/display/TCGA/TCGA+barcode

(not actually recommending that level of detail, but could be useful for ideas)

**Comment by kdaily** [comment]
I'm (for specific projects) advocating for the use of UUID generators. The simplest (but full featured) comes as part of the Python standard library, supports namespaces, etc. They're not "human readable" like TCGA barcodes.

There's an interesting (though not available) service from NDA (https://data-archive.nimh.nih.gov/guid/) applicable to generating global individual (human) identifiers.

Quoting someone there:

"Supporting the GUID for other groups is on our roadmap but we haven’t gotten to it yet.  There’s some policy/funding challenges for us to overcome here at the NIH that need to be addressed.  In the meantime, have those groups talk to us. We really want someone to champion this need, even if it isn’t us.  It’s needed and should be supported by the NIH as a trusted provider."
