### ISSUE TITLE
Data-type specific annotations

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseAnnotations#57]
I realize that a lot of projects are very omics focused but was wondering if it makes sense to expand the minified on a data-type specific fashion. For example, have a NGS-based annotation schema, a microscopy-based schema. etc.  There are terms from neuro that are highly applicable across studies and we could make it easier to jump on the annotations bandwagon if we had a set of ready-to-go schemas for future users.

**Comment by amapeters** [comment]
NGS annotation schema submitted - see pull request
