### ISSUE TITLE
Documentation for using csv to maintain schema.org schemas

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/synapseAnnotations#592]
Document what
- does each of the columns in the csv do wrt schema.org schema; wrt validation schemas; wrt manifests
- do different csv rows represent 
- are the main interactions between columns in the csv

**Comment by cw-dvr8** [comment]
Initial draft in progress: https://docs.google.com/document/d/1WLae-yU6PqhdPK7sun_2UJjNeVS2b4p_AKEZJrMJBmA/edit

**Comment by cw-dvr8** [comment]
Ran into some issues getting the requirements.txt to install.  Steps I took to resolve them can be found here: https://docs.google.com/document/d/124rJJY1Tv6oVr-m9fyLbPJvKsOYVB7XCGrS1heJSzto/edit

**Comment by milen-sage** [comment]
Thanks! This will be resolved in an update that refactors the structure of the code and changes the installation process to a more standard python setup, where dependencies contain only the exact requirements for the package. Should be ready this week.

**Comment by milen-sage** [comment]
Documentation is evolving here (see section 'JSON-LD schema creation'):
https://docs.google.com/document/d/1MoTVogc5JouziQ9i7otf74qzBRIBHHNCJda6NAbRU_M/edit?usp=sharing
