### ISSUE TITLE
Workflow for maintaining multiple data models across consortia

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/synapseAnnotations#594]
How do we handle different schemas representing differences between data models used in different consortia/projects in Sage?

**Comment by karawoo** [comment]
@milen-sage's proposal:
- Add `context` column which has `sage.schema.core` for base things, then `amp-ad` and other consortia for consortium-specific things
- Rows in csv still indicate keys, values, and there's a row for the consortium that in the "requires" column lists the required keys for that consortium's schema
  - Code to generate schema would look in amp-ad (or whichever consortium) context first for each term, if not there then would go up to sage.schema.core
  - Required fields themselves might then have their own requirements that would get pulled into the validation schema as well

**Comment by allaway** [comment]
Had a conversation with @milen-sage today and he pointed me to this issue to provide a different use case for contextual values. Reading this issue more closely, it sounds like this could be an independent but related issue, so happy to file separately if needed. 

We'd like to be able to support a scenario where there are keys that have multiple potential contexts, and for each context there is a different valid subset of values can be derived from. An example is the relationship between the `assay` and `dataType` keys, which describe related concepts. 

As an example,  If I have a contributor that annotates the `resourceType` as `experimentalData`, we then require `dataType`.  They then put `dataType = genomicVariants` and we require `assay'` However, we only want to validate based on (and, ideally, if this is annotation happening in a dynamically updating interface, present) only the subset of `assay` values that are applicable to the `genomicVariants` `dataType` (e.g. `polymeraseChainReaction,wholeExomeSeq,wholeGenomeSeq...`).

**Comment by karawoo** [comment]
I think this is handled for now by having "canonical" terms registered under the sage.annotations organization, and having projects write schemas that reference those terms or alternate project-specific terms as needed.
