### ISSUE TITLE
Simplify directory structure

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseAnnotations#612]
The schemaorg-conversion-v2 branch adds additional requirements and tests. We now have requirements in `requirements.txt` and `synapseAnnotations/requirements.txt`, and tests in `tests/integration/` and `synapseAnnotations/tests` (only the former are run by Travis). @milen-sage, would it be possible to consolidate these? I'm not familiar with the correct structure for Python packages, but if you fill me in I can also make the change and open a PR.

**Comment by milen-sage** [comment]
We are currently refactoring and packaging the schema code, and I will push the updates to this repo as well after that's done. The overall schema-related directory structure and tests will change after the refactor (~1 week). I will consolidate the requirements and tests after that unless it's too much of an annoyance?

**Comment by karawoo** [comment]
Sounds good, thanks!

**Comment by karawoo** [comment]
Just wanted to check back on on progress on this issue. @milen-sage do you have any updates?
