### ISSUE TITLE
All source references to HCA library_preparation_process.json are broken

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/synapseAnnotations#614]
example here: 
https://github.com/Sage-Bionetworks/synapseAnnotations/blob/c4c0f4f25c48271877cd596b6356891edbacf1b8/synapseAnnotations/data/ngs.json#L173

**Comment by karawoo** [comment]
This is a duplicate of #426 so I'm going to close this one

**Comment by allaway** [comment]
Ah, sorry about that. I just came across it when trying to looking for more
information this morning and hastily filed the issue! 🙂
