### ISSUE TITLE
Cross-column derivations/actions

### ISSUE THREAD

**Issue by cw-dvr8** [Sage-Bionetworks/synapseAnnotations#617]
The VEOIBD clinical metadata has a column for site abbreviation, a column for local ID, and a consortium participant ID column which is a concatenation of the other two columns.  For example:

site abbreviation = TOR
local ID = 12345
consortium participant ID = TOR12345

It would be useful to have some method in the Google sheet generated from the JSON-LD schema to define that consortium ID is derived from site abbreviation plus local ID so that the column would autofill when users have enter values for the other two.

In the same vein, it would be useful to be able to make a column required based on the values of more than one column.  For example, PsychENCODE individual data has an "otherDiagnosisDetail" field that is only required if species = "Human" and otherDiagnosis is not null.

**Comment by karawoo** [comment]
I think the first point here is more of a schematic issue, and I think the second is doable with JSON schema.
