### ISSUE TITLE
Drop down list length - export to Excel

### ISSUE THREAD

**Issue by cw-dvr8** [Sage-Bionetworks/synapseAnnotations#618]
The VEOIBD clinical metadata schema contains a column called countryOfOrigin that the consortium has requested contain the name of each country in the world.  This is running into some sort of character or list length limit when the Google Sheet is exported to Excel.  In Excel the countryOfOrigin column will prompt the user to select from the drop down list, but then the list attached to the column is blank.

**Comment by milen-sage** [comment]
This is now fixed to address https://github.com/Sage-Bionetworks/HTAN_data_curator/issues/64 via https://github.com/Sage-Bionetworks/schematic/pull/323
