### ISSUE TITLE
Remap manifest column values

### ISSUE THREAD

**Issue by cw-dvr8** [Sage-Bionetworks/synapseAnnotations#619]
There needs to be a method for remapping manifest column values to different/standardized values.  For example, in the VEOIBD clinical metadata there is a conditional requirement for the breastFedDuration column if the value of the breastFed column is "Yes".  However, there are other columns in the metadata where "Yes" is valid (consanguinity, exposureSecondhandSmoke, etc.) so the value of the breastFed column has to be defined as "Yes - Breast Fed" in the csv file and the schema so that the manifest that gets generated correctly indicates the conditional requirement based on only the value in the breastFed column.  For consistent querying and annotations, we need to be able to map "Yes - Breast Fed" in the completed metadata template back to just "Yes".

**Comment by karawoo** [comment]
I believe our switch to JSON Schema here has addressed this; feel free to reopen if not
