### ISSUE TITLE
Review new metadata terms per 11Jan2021 call

### ISSUE THREAD

**Issue by cw-dvr8** [Sage-Bionetworks/synapseAnnotations#701]
We need input from @amapeters for the following new metadata terms that were discussed on the call on 11Jan2021:

bindingDensity (AMP) (Number of fluorescent spots per micrometer squared of the lane surface (https://www.genetics.pitt.edu/sites/default/files/pdfs/nCounter_Gene_Expression_Data_Analysis_Guidelines.pdf).)
- which module does this belong in?

geneRLF (AMP) (Reporter Library File (RLF) used to associate gene names with counts specified by the user in the Cartridge Definition File (https://www.genetics.pitt.edu/sites/default/files/pdfs/nCounter_Gene_Expression_Data_Analysis_Guidelines.pdf))
- which module does this belong in?

nanostringBatch (AMP)
- What would be a good description of this?

temperature (AMP) (Temperature in which Drosophila were raised)
- Should we keep this description or should we make it more generic so that it can be used for other purposes?
- which module does this belong in?

**Comment by amapeters** [comment]
> bindingDensity (AMP) (Number of fluorescent spots per micrometer squared of the lane surface (https://www.genetics.pitt.edu/sites/default/files/pdfs/nCounter_Gene_Expression_Data_Analysis_Guidelines.pdf).)
> 
> * which module does this belong in?

This should go into the QC module. 

I suggest changing the description to: "The Binding Density is a measure of the number of optical features per square micron, it is useful for determining whether or not data collection has been compromised due to image saturation. Typical range is 0.05 and 2.25."

**Comment by amapeters** [comment]
> geneRLF (AMP) (Reporter Library File (RLF) used to associate gene names with counts specified by the user in the Cartridge Definition File (https://www.genetics.pitt.edu/sites/default/files/pdfs/nCounter_Gene_Expression_Data_Analysis_Guidelines.pdf))
> 
> * which module does this belong in?

Put it in experimental data

**Comment by amapeters** [comment]
> nanostringBatch (AMP)
> 
> * What would be a good description of this?
Following up with data provider about this

**Comment by amapeters** [comment]
> temperature (AMP) (Temperature in which Drosophila were raised)
> 
> * Should we keep this description or should we make it more generic so that it can be used for other purposes?
How about "temperature relevant to specimen or experimental condition"
> * which module does this belong in?
Experimental data

**Comment by Aryllen** [comment]
Closing since these were added.
