### ISSUE TITLE
Create tool/workflow annotations

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/synapseAnnotations#83]
This will encompass keys/terms to describe tools used in and shared by a project such that they can be easily viewed and queried similar to other files.

Some potential information to consider:

- tool name
- tool version
- tags
- tool type
- language / platform
- source
- application(s)
- container available?
- in tool registry?

And probably others we'll think of as we go.

Worth paying attention to related efforts by GA4GH, Dockstore, Biocontainers, et al.

**Comment by sgosline** [comment]
"workflows" I'd like to support include:

- basic scripts uploaded to synapse
-R/python package links 
-dockerized images
-gitHub repos

**Comment by sgosline** [comment]
We'll take a first pass at a schema to support this.  First pass will be to store everything as a file entity with a link to the relevant tool.

**Comment by jaeddy** [comment]
Getting started here:
https://github.com/Sage-Bionetworks/synapseAnnotations/blob/add-tool-annotations/synapseAnnotations/data/tool_annotations.json

Feedback welcome.

**Comment by sgosline** [comment]
@jaeddy should we close this for now?
