### ISSUE TITLE
Enhancement to ATACSeq template to include scATACSeq values

### ISSUE THREAD

**Issue by pitviper6** [Sage-Bionetworks/synapseAnnotations#911]
## _Single-cell ATAC-seq data are sparse and noisy_

Article on scATACSeq methods: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02075-3
Existing template (ATACSeq): https://www.synapse.org/#!Synapse:syn22024364
Requested template: scATACSeq

Current keys:

specimenID | libraryID | assay | platform | referenceSet | transposaseBatch | libraryBatch | libraryPreparationMethod | pcrCycles | sequencingBatch | isStranded | readStrandOrigin | readLength | runType | meanCoverage | meanGCContent

Keys suggested by data contributors:

Q30 bases in read 1
Q30 bases in read 2
barcode
sample index

**Comment by pitviper6** [comment]
@amapeters @ryaxley @avanlinden @danlu1 Please add your comments questions by Friday, April 15. If I don't get comments, I will add the listed new keys to the current ATACSeq template and create a new value = scATACSeq for the assay key.

**Comment by avanlinden** [comment]
Moved this issue to sysbioDCCjsonschemas repo, closing this one. https://github.com/Sage-Bionetworks/sysbioDCCjsonschemas/issues/137
